version: '2'

services:
    elasticsearch:
        image: elasticsearch
        ports:
            - 9200:9200
            - 9300:9300

    fpm:
        build: docker/php-fpm/
        links:
            - memcached
            - mysql
            - mongo
            - rabbitmq
            - redis
        volumes:
            - ./:/var/www/symfony
            - ./docker/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini

    memcached:
        image: memcached
        ports:
            - 11211:11211

    mysql:
        image: mysql
        environment:
            MYSQL_DATABASE: devdb
            MYSQL_USER: devdb
            MYSQL_PASSWORD: devdb
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
        ports:
            - 33060:3306

    mongo:
        image: mongo
        ports:
            - 27017:27017

    nginx:
        image: nginx
        ports:
            - 8086:80
        volumes:
            - ./:/var/www/symfony
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        links:
            - fpm
            - varnish

    rabbitmq:
        image: rabbitmq:3.6.1-management
        ports:
            - 15672:15672
            - 5672:5672
        environment:
            RABBITMQ_DEFAULT_PASS: root
            RABBITMQ_DEFAULT_USER: root

    redis:
        image: redis:latest

    varnish:
        # build: docker/varnish/
        image: newsdev/varnish:4.1.0
        ports:
            - 8087:8087
            - 8080:80
        environment:
            VARNISH_PORT: 8087
            VARNISH_MEMORY: 1G
        links:
            - nginx
